<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function getTasksUpdatedBefore($date)
    {
        $rsm = new ResultSetMappingBuilder($this->getEntityManager());
        $rsm->addRootEntityFromClassMetadata('AppBundle\Entity\Task', 'u');
        return $this->getEntityManager()->createNativeQuery("SELECT * FROM u where updated < '$date';", $rsm)->getResult();
    }

    public function getTasksByIds($ids)
    {
        $tasks = array();

        foreach ($ids as $id) {
            $tasks[] = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('task')
                ->from('AppBundle:Task', 'task')
                ->where('task.id = \'' . $id . '\'')
                ->getQuery()
                ->getSingleResult();
        }
        return $tasks;
    }
}
